id: A9156C5CC
base_file: fC6BD.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:56:21.294390
  last_modified_at: 2022-05-30 18:56:21.294396
